### ISSUE TITLE
[UI] - Broken Section

### ISSUE THREAD

**Issue by ank1traj** [rtCamp/blogger-to-wordpress#23]
## Bug Report

**Testing Environment -**
**OS** - Mac OS
**Browser** - Chrome 
**URL** - https://bloggertowp.org/

**Current Behavior**
- Section before **Do It Yourself Migration Guide** is looking broken

![image](https://user-images.githubusercontent.com/32160084/142225241-c8598e13-e62b-481c-9e62-c28986a26c18.png)

**Expected behaviour/code**
- Section should not be broken

**Comment by devansh016** [comment]
@ank1traj , Thanks for the bug report.
This has already been fixed. Ref: #26

<img width="1162" alt="Screenshot 2024-07-19 at 11 07 10 AM" src="https://github.com/user-attachments/assets/4ff562f5-65ac-459e-bed9-054836a06ab4">
