### ISSUE TITLE
PHP Deprecated warnings are visible with the PHP8.1

### ISSUE THREAD

**Issue by pavanpatil1** [rtCamp/blogger-to-wordpress#35]
The PHP Deprecated warnings are visible with the PHP8.1

`[10-Sep-2023 20:33:16 UTC] PHP Deprecated:  Function has_cap was called with an argument that is <strong>deprecated</strong> since version 2.0.0! Usage of user levels is deprecated. Use capabilities instead. in /wp-includes/functions.php on line 5737`

PHP8.1 compatibility report - https://plugintests.com/plugins/wporg/blogger-to-wordpress/latest

**Comment by pavanpatil1** [comment]
Hi @NikhilJoshua, yes the folder is not related but could please check - `has_cap`  and `wpdb::escape`  function is used anywhere in the plugin. Warning is related to that function.

**Comment by NikhilJoshua** [comment]
@pavanpatil1 
Couldn't find any file which is using `has_cap` in the codebase. I think it's related to WordPress Core.
![image](https://github.com/rtCamp/blogger-to-wordpress/assets/8474784/cbf5ef3a-1197-4226-b611-ce6b2f136b08)

**Comment by pavanpatil1** [comment]
Hi @NikhilJoshua, could you please check this - 

`PHP Warning:  Undefined array key "blogUrl" in /wp-content/plugins/blogger-to-wordpress/wp-blogger-to-wordpress.php on line 62`

**Comment by devansh016** [comment]
Hi @pavanpatil1,

I've investigated the issue you reported. After reviewing the compatibility report and searching for the file path, I've found that:

1. The file `/wp-content/plugins/blogger-to-wordpress/wp-blogger-to-wordpress.php` doesn't exist in our codebase.

2. The compatibility report you mentioned is for a different plugin than the one we maintain. It refers to [blogger-to-wordpress](https://wordpress.org/plugins/blogger-to-wordpress/), not our [blogger-to-wordpress-redirection (rtCamp)](https://en-gb.wordpress.org/plugins/blogger-to-wordpress-redirection/).

3. I've checked the compatibility report for our plugin: https://plugintests.com/plugins/wporg/blogger-to-wordpress-redirection/latest

This report shows no PHP errors, warnings, or notices for our plugin.

Given these findings, I believe we can close this issue. The reported warning seems unrelated to our plugin. Let me know if you need any further clarification.
