### ISSUE TITLE
Facebook link and logo not visible properly on settings page

### ISSUE THREAD

**Issue by pavanpatil1** [rtCamp/blogger-to-wordpress#37]
On the settings page, the logo and link is not visible properly. 

![image](https://github.com/rtCamp/blogger-to-wordpress/assets/44057535/fee1ddd1-7293-4a15-b171-dd466eb746b3)

**Comment by NikhilJoshua** [comment]
@pavanpatil1 working fine in my local, can you please check in different system?
![image](https://github.com/rtCamp/blogger-to-wordpress/assets/8474784/b8cb97a4-245e-4d5c-9363-acbabcab6ce9)
