### ISSUE TITLE
Get code button not working to get code for another blogs

### ISSUE THREAD

**Issue by Sourav61** [rtCamp/blogger-to-wordpress#42]
### Testing Environment -
```
OS - Mac OS
Browser - Chrome
URL - https://bloggertowp.org/
```

### Current Behaviour

- When using the Blogger to WordPress Plugin, the Get code button only works for 1st time after clicking the Start configuration button.
- To switch from one blog to another for obtaining configuration details, the get code button does not seem to be working, as shown in the video below.

Video Link: https://app.screencastify.com/v3/watch/wvmX9Vpf3ap8CIyE3nWk

### Expected behaviour/code

- The Get Code button should be able to provide configuration details for each blog in Blogger to WordPress Redirection tools.

**Comment by devansh016** [comment]
Fixed in version 2.3.1
