### ISSUE TITLE
Plugin update and compatibility check (July 2024)

### ISSUE THREAD

**Issue by dhawalepranav** [rtCamp/blogger-to-wordpress#43]
We need to complete the following set of tasks for [Blogger to Wordpress](https://wordpress.org/plugins/blogger-to-wordpress-redirection/).

- [x] Make sure it's compatible with the latest WordPress version. (e.g 6.6.X )
- [x] Make sure it's PHP 8.2 compatible. (Let's test it with 8.3 as well)
- [x] Make sure it's VIP compatible
- [x] Run the PHPCS scan
- [x] Review the open GH issues and close them with resolution.
- [x] Document the user manual with screenshots that will include things like "How to install plugin", "Plugin Pre-requisites" "How to setup plugin for first time", "Plugin Settings with their use case" etc

Before starting the work please add your time estimations for every mentioned task and get it approved by your Project Co-ordinator or Project Manager

**Comment by devansh016** [comment]
### Time Estimation: `35 - 45h` 

## Plan of Action:
- Getting familiar with the plugin
- Compatible check with the latest WordPress version 6.6
- Compatible check with PHP 8.2 and 8.3
- Compatible check for VIP
- Run the PHPCS scan and fix PHPCS warnings and errors
- Review the open GH issues and close them with resolution **(~ 15h already included in time estimate)**
- Document the user manual with screenshots that will include things like "How to install plugin", "Plugin Pre-requisites" "How to setup plugin for first time", "Plugin Settings with their use case" etc
- Test functionality and update plugin

**Comment by dhawalepranav** [comment]
@devansh016 What's the status of this task? Can you please add a milestone update here? Thanks!

**Comment by devansh016** [comment]
@dhawalepranav 
Currently working on making the plugin VIP compatible and after that will test and update the plugin.

✅ Getting familiar with the plugin
✅ Compatible check with the latest WordPress version 6.6
✅ Compatible check with PHP 8.2 and 8.3
-- Compatible check for VIP (fixing compatibility issues)
✅ Run the PHPCS scan and fix PHPCS warnings and errors
✅ Review the open GH issues and close them with resolution
✅ Document the user manual with screenshots that will include things like "How to install plugin", "Plugin Pre-requisites" "How to setup plugin for first time", "Plugin Settings with their use case" etc **(no changes here already well documented and upto date)**
-- Test functionality and update plugin

**Comment by devansh016** [comment]
Plugin update release on 23rd August.
